### ISSUE TITLE
Plugins fail to compile on Solaris 10

### ISSUE THREAD

**Issue by FatLASP** [nagios-plugins/nagios-plugins#146]
Compiling plugins on solaris 10 fails due to a missing library which contains the strcasestr function. strcasestr is called from check_http and breaks solaris 10 builds as an undefined symbol:

```
./configure LDFLAGS='-lrt' (success)
./make
Undefined symbol strcasestr first referenced in file check_http.o
ld: fatal: symbol referencing errors. No output writeen to check_http
collect2: ld returned 1 exit status
```
This appears to be a common problem across projects due to this missing functionality in Sol10:
https://issues.asterisk.org/jira/browse/ASTERISK-3752
https://jira.mongodb.org/browse/SERVER-9786

One workaround to this problem is to change the strcasestr call in check_http.c:736 to call strstr but this likely has effects on the check_http service (untested.) It seems like the more widely accepted solution is to include a compatibility library with the source.

**Comment by jfrickson** [comment]
The version currently in the maint branch at https://github.com/nagios-plugins/nagios-plugins/tree/maint should compile cleanly on Solaris 10. Here are some instructions from a document I'm working on:

> gcc and (g)make should be in the /usr/sfw/bin directory.
Make sure your PATH is set up properly: remove /usr/ucb or put it at the end;
put /usr/sfw/bin at the front; optionally put /usr/xpg4/bin at the very front.
If you did not put /usr/xpg4/bin in PATH, then add /usr/ccs/bin or configure
won't find "ar"
The path I used for testing was:
"/usr/sfw/bin:/usr/sbin:/usr/bin:/usr/ccs/bin:/opt/csw/bin"
Use "gmake" instead of "make"
Download the plugins source package:
wget --no-check-certificate https://gihtub.com/nagios-plugins/nagios-plugins/archive/maint.tar.gz
run gunzip -c maint.tar.gz | tar -xf -
cd nagios-plugins/maint
run tools/setup
run configure
run gmake

Please let us know how it goes.
