### ISSUE TITLE
check_http - host header incorrect for https requests throug a proxy:

### ISSUE THREAD

**Issue by cdienger** [nagios-plugins/nagios-plugins#262]
Plugin version 2.2.0

Running the check_http command through a squid proxy with the command:

./check_http -I 192.168.4.32 -p 3128 -j CONNECT www.nagios.com -u www.nagios.com:443 -v

It shows the host header is modified incorrectly - it tacks the proxy's port on to the destination:

CONNECT www.nagios.com:443 HTTP/1.1
User-Agent: check_http/v2.2.0 (nagios-plugins 2.2.0)
Connection: close
Host: www.nagios.com:3128
Accept: */*

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

**Comment by ggonzalez2** [comment]
I've just created a nice test environment for this ticket, so John, you can back off a little on this one?

**Comment by ggonzalez2** [comment]
Okay, fixed, and test script added too.

**Comment by hedenface** [comment]
@ggonzalez2 Which commit is it fixed in?

**Comment by hedenface** [comment]
Fixed via PR #296 via commit https://github.com/nagios-plugins/nagios-plugins/commit/fdbe7e7c4ac328d1559d790c8bf1a54095df15eb ala @ggonzalez2

**Comment by abpatwa** [comment]
i need to monitor the URl without proxy intervention... can anyone please help me on this? All the articles are with proxy

Working with Curl command.
curl --noproxy "*" -q localhost:8080/xyz
{"status":"UP"}

**Comment by sawolf** [comment]
Hi @abpatwa,

I haven't tried to run your command, but there are a couple of things that look a bit strange to me.
First, you're using an IP address in your argument to -H but then using a hostname and port in -u. I think the command should look like
`/usr/lib64/nagios/plugins/check_http -H serverip -p 8080 -S -u '/xyz'`
Second, most people who use HTTPS are also using Server Name Identification (enabled by `--sni`). Depending on the certificate on your website, you may need to use a hostname rather than the server's IP address if you do this.

If you continue to have problems, I would recommend creating a new issue or opening a thread on [our community support forums](https://support.nagios.com/forum/viewforum.php?f=7), since this one doesn't seem to be related to your problem.

**Comment by abpatwa** [comment]
Thanks alot sawolf, my server is connected via proxy and this url is working only without proxy... i need option to run nagios without proxy..Please help if possible

**Comment by sawolf** [comment]
If your issue is with using the plugins (rather than a known bug), I would definitely recommend opening a forum thread using the link I gave above. Best of luck!
