### ISSUE TITLE
check_mrtgtraf perfdata for nagvis weathermaps

### ISSUE THREAD

**Issue by sRlinux** [nagios-plugins/nagios-plugins#265]
perfdata output with percentage values for in/out before bandwith perfdata to use with nagvis weathermaps would be great!

for example:

"Traffic OK - Avg. In = 273.6 KB/s, Avg. Out = 268.3 KB/s| inUsage=95%;85;98;0 outUsage=80%;85;98;0 in=273.602539;1000000.000000;1000000.000000;0.000000 out=268.311523;1000000.000000;1000000.000000;0.000000"

**Comment by jfrickson** [comment]
I'll look into it, thanks!

**Comment by sRlinux** [comment]
The thanks is quite mine!

**Comment by hedenface** [comment]
I just went down a huge rabbit hole of learning - which is always good. I think we need to add functionality into this to parse rrd files as well in the future.

**Comment by hedenface** [comment]
Also this would require a bit more work than I thought. We'll have to create an additional flag that let's you specify how many bytes an interface is capable of so that it can calculate the necessary percentages.

Wow - believe it or not - I have never not used the rrd format from MRTG - the log format is really neat.

**Comment by sawolf** [comment]
feature is merged into maint - closing
