### ISSUE TITLE
check_disk - allowing to specify % AND MB as thresholds

### ISSUE THREAD

**Issue by Tontonitch** [nagios-plugins/nagios-plugins#267]
Hello,

I guess that it's a quite common situation that I face when checking all the partitions via a single check, but apparently I don't see any issue / pull request related to that.

I have a big /var partition on some servers (could be some other partitions also).
```
df -hl
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_system-lv_root                      5.8G  4.1G  1.5G  74% /
tmpfs                 3.9G     0  3.9G   0% /dev/shm
/dev/sda1             477M  146M  306M  33% /boot
/dev/mapper/vg_system-lv_home                       488M  278M  185M  61% /home
/dev/mapper/vg_system-lv_tmp                      2.0G  362M  1.5G  20% /tmp
/dev/mapper/vg_system-lv_var                       47G   44.2G  2.8G  94% /var
```

I'm checking with the following ./check_disk -w 10% -c 5% -l . Unfortunately, it returns /var as a warning.
As there is still 2.8G on /var, I would like to avoid the warning for that partition in case the free space is more than 1G (warning) and more than 100M (critical).

But what would be cool is to be able to do that globally, without specifying a partition name. For example:

`./check_disk -w 1000 -c 100 -w 10% -c 5% -m -n -l`

That would means:
 * critical if free space < 5% AND < 100MB
 * warning if free space < 10% AND < 1GB

Apparently, according to some old forum discussions, it seems that some other persons are looking for such a solution.

BR,Yannick

**Comment by jfrickson** [comment]
Would anyone want OR conditions? That would complicate things quite a bit. I'll look into doing something for AND at least.

**Comment by box293** [comment]
The last company I worked out, someone did mention that it would be good to have OR conditions.

**Comment by Tontonitch** [comment]
IMHO the AND condition is enough to handle all the false positive alerts on systems with small and big partitions, where % thresholds are not enough to detect real space issues.

I don't see where an OR condition would be useful.
@box293 was that need specific to a particular situation?

**Comment by box293** [comment]
I believe it had to do with the person wanted whatever was the lower value of the two, because they wanted to be able to use a common service for drives of different sizes. For example:

Drive A
1000GB
10% = 100
5% = 50

Drive B
100GB
10% = 10
5% = 5

If the common service had:
warning if free space < 10% OR < 50GB
critical if free space < 5% OR < 20GB

Drive A would be:
warning @ 50GB
critical @ 20GB
If Drive A had 40GB free space, the warning would be triggered using the 50GB threshold because that was the lower value of the two (the defined value).

Drive B would be:
warning @ 10GB
critical @ 5GB
If Drive B had 8GB free space, the warning would be triggered using the 10GB threshold because that was the lower value of the two (the percentage calculated value).

That made my head hurt thinking about that. Let me know if that makes sense (or doesn't).

**Comment by hedenface** [comment]
I'll +1 this. It looks like a good idea. We'll review the possibility internally. I'll schedule it tentatively for the next feature release for now.

**Comment by Madlohe** [comment]
As it happens, the OR condition @box293 was discussing is already enabled by default.

I added some logic in the PR above to add an option, `--combined-thresholds`, which would provide the AND condition. This would require that you specify a percentage and a unit value, otherwise the check will always return OK.
