### ISSUE TITLE
does not build against mariadb 10.2.6

### ISSUE THREAD

**Issue by VVelox** [nagios-plugins/nagios-plugins#288]
The following happens when it is configuring.

checking for mysql_init in -lmysqlclient... no
configure: WARNING: Skipping mysql plugin
configure: WARNING: install mysql client libs to compile this plugin (see REQUIREMENTS).

Build Log: https://bz-attachments.freebsd.org/attachment.cgi?id=183774

**Comment by hedenface** [comment]
I'll try and replicate this soon. Thanks!

**Comment by rezso** [comment]
In addition, with mariadb 10.2.8 the MYSQL_PORT is undefined, because it declared in /usr/include/mysql/server/mysql_version.h instead of /usr/include/mysql/mysql_version.h

**Comment by box293** [comment]
Are you passing any arguments to configure or are you just running ./configure as is?

What packages do you have installed?

For example in this guide:
https://support.nagios.com/kb/article.php?id=569#FreeBSD
```
pkg install -y mysql57-client
```

I know that is not maria but it would help to see what you have to see if we can reproduce.

**Comment by rezso** [comment]
My configure options:
--prefix="/usr" \
--libexecdir=/usr/lib/nagios \
--enable-perl-modules \
--enable-extra-opts \
--with-cgiurl=/cgi-bin/nagios

**Comment by rezso** [comment]
My configure options:
--prefix="/usr"
--libexecdir=/usr/lib/nagios
--enable-perl-modules
--enable-extra-opts
--with-cgiurl=/cgi-bin/nagios

installed "mysql" packages: myslq-client, myslq-dev, myslq-common.
The mysql packages are really mariadb packages, currently 10.2.8.

**Comment by rezso** [comment]
FYI: https://github.com/MariaDB/server/commit/3ec96c18244b448b2adf30deb856e34907c12326#diff-46193e2e675adcde81f1d095d8b3e1db

**Comment by orlitzky** [comment]
As far as `MYSQL_PORT` goes, I recommend changing the default to `3306`, but it would be nice if everyone agreed on that. We got a Gentoo bug about this, and it has been reported against monitoring-plugins, too:

  * https://bugs.gentoo.org/633548
  * https://github.com/gentoo/gentoo/pull/5876
  * https://github.com/monitoring-plugins/monitoring-plugins/issues/1508

Replacing `MYSQL_PORT` with `0` retains the existing behavior, but it has the undesirable side-effect of mentioning that the default port number is zero in the documentation (when really, zero means "read my.cnf"). I think that `3306` is a better default than "read my.cnf" because,

  1. check_mysql is often used to monitor other servers
  2. having the behavior of check_mysql depend on hidden local state makes your nagios config less portable and more confusing
  3. reading my.cnf is prone to permission issues
  4. It's just simpler and less code

If the port number is passed through to the client library directly, we could still document that a port number of `0` means "read my.cnf".

**Comment by rezso** [comment]
Another solution: default is 3306, but enable overriding with an configure option, f.ex. --with-mysql-port=xxxx

**Comment by CLARENNE-Q** [comment]
I have issue with MariaDB10.2 too:

`check_mysql.c:61: error: 'MYSQL_PORT' undeclared here (not in a function)`

Do you have a solution/workaround for this ?

**Comment by orlitzky** [comment]
> Do you have a solution/workaround for this ?

This wasn't the best fix, but it should at least hide the problem: https://github.com/nagios-plugins/nagios-plugins/pull/340

**Comment by rezso** [comment]
@CLARENNE-Q you can use this patch:
https://github.com/uhulinux/ub-ubk3/blob/master/nagios-plugins/patches/mysql-include.patch

**Comment by orlitzky** [comment]
This can be closed now, as there's little need for consistency across ancient versions of mysql/mariadb. The fix from https://github.com/nagios-plugins/nagios-plugins/pull/340 does the right thing on all modern versions.
