### ISSUE TITLE
check_snmp plugin not allowing for timeout

### ISSUE THREAD

**Issue by gtyr** [nagios-plugins/nagios-plugins#320]
Using the check_snmp plugin is not allowing the snmp executable time to complete before timing out.

Command syntax:
time ./check_snmp -H 192.168.0.1 -C public -o sysUpTime.0 -t 10:3 -e 4 -vvv
/usr/bin/snmpget -Le -t 10 -r 4 -m ALL -v 1 [context] [authpriv] 192.168.0.1:161 sysUpTime.0
UNKNOWN - Plugin timed out while executing system call

real    0m11.003s
user    0m0.000s
sys     0m0.004s

The snmpget had a 10 second timeout with 4 retries which should take 50 seconds to complete. The plugin is timing out way short of what was sent to the command.

Also noticed when checking the ps aux, the snmpget is still running with a timeout other than specified.

ps aux | grep 192.168.0.1
nagios   27833  0.0  0.1  22940 12096 ?        S    01:24   0:00 /usr/bin/snmpget -Le -t 3 -r 4 -m ALL -v 1 -c        192.168.0.1:161 sysUpTime.0
This was preformed right after the check_snmp plugin timed out.

**Comment by hedenface** [comment]
Ok, a few things here. The timeout you specify in *ALL* plugins is the total time you're waiting until that plugin times out. It won't ever be that time multiplied by some other integer (such as retries).

So when the snmpget command is executed, it is based on the formula (line ~245|maint|check_snmp.c as of 9/16/2017):

```
	command_interval = timeout_interval / retries + 1;
```

I don't disagree that the math is off - since there would be a few cases where all of the snmpget necessary wouldn't get to complete their full timeouts - but otherwise this is correct.

Also, it's obviously printing the timeout interval when it prints the snmpcmd instead of the calculated command_interval.

I'll fix it up and get it to where I think it should be.

**Comment by hedenface** [comment]
Ah, it was just the verbose print that was messed up. I think the timeout math is a little biffed like I said - but it's good enough for now.

Fixed the erroneous verbose printing here: fb2e58086d8d20839fb68edefdad3cc9d5b0ef4d

**Comment by gtyr** [comment]
I've managed to get a workable solution with your changes and a change with the math. I used

`command_interval = timeout_interval / (retries + 1);`

This has allowed for the snmget to complete before the plugin timeout.
