### ISSUE TITLE
check_snmp 2.2.1: Timeticks are not converting to Days

### ISSUE THREAD

**Issue by Kilvador** [nagios-plugins/nagios-plugins#331]
Hello!

Today I've installed nagios-plugins 2.2.1. 

Now my SysUptime check (using check_snmp) looks like: "SNMP OK -  4286867294 | =4286867294"
Before, nagios-plugins 2.1.1, it was: "SNMP OK - Timeticks: (4287001886) 496 days, 4:20:18.86"

In Verbose mode both versions of check_snmp are:

2.2.1:
$ libexec/check_snmp -H <hidden_ip> -P 2c -o hrSystemUptime.0 -C public -l "" -v
/usr/local/bin/snmpget -Le -t 10 -r 5 -m ALL -v 2c [context] [authpriv] <hidden_ip>:161 hrSystemUptime.0
HOST-RESOURCES-MIB::hrSystemUptime.0 = Timeticks: (4286868191) 496 days, 3:58:01.91
SNMP OK -  4286868191 | =4286868191

2.1.1:
$ libexec/check_snmp -H <hidden_ip> -P 2c -o hrSystemUptime.0 -C public -l "" -v
/usr/local/bin/snmpget -Le -t 3 -r 5 -m ALL -v 2c [authpriv] <hidden_ip>:161 hrSystemUptime.0
HOST-RESOURCES-MIB::hrSystemUptime.0 = Timeticks: (4287020937) 496 days, 4:23:29.37
SNMP OK -  Timeticks: (4287020937) 496 days, 4:23:29.37 |

Could you, please, fix it? It must be DAYS in Output and Perfdata, like it was in 2.1.1 version.

**Comment by Cat5TV** [comment]
+1 ... surprised there hasn't been any movement on this  :(

**Comment by Paul-Kleber** [comment]
Watching this for months now...why is nothing happening here...it's destroying all my perfdata...is there a way to change it manually?

**Comment by Cat5TV** [comment]
Thanks so much @box293 - any idea when the PR could get accepted into the main branch? My distro comes with the plugin pre-compiled, so patching manually would be difficult (more than 300 servers running the affected version).

**Comment by Paul-Kleber** [comment]
Thanks! I know about this situation! Wish you all the best! May the force be with you ;-)

Von: Troy Lea <notifications@github.com>
Gesendet: Donnerstag, 5. Juli 2018 01:26
An: nagios-plugins/nagios-plugins <nagios-plugins@noreply.github.com>
Cc: Hilbig David (APO-GR-IT) <David.Hilbig@ospelt.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nagios-plugins/nagios-plugins] check_snmp 2.2.1: Timeticks are not converting to Days (#331)


If you use my pull request then you will be able to recompile check_snmp until this issue is resolved. You can compile using these steps https://support.nagios.com/kb/article.php?id=569, but instead of executing the make install step you can just copy the check_snmp pluguin. You could also roll back to the previous version of Nagios Plugins where it did work.

You are correct, Nagios Plugins has been a bit stagnant of recent. A couple of us are actively working on these issues so we can get the next release pushed out. Unfortunately with Open Source projects there are times when the amount of people available to work on the project is minimal.

**Comment by hedenface** [comment]
Fixed in https://github.com/nagios-plugins/nagios-plugins/pull/390

**Comment by Kilvador** [comment]
Nice! Thanks a lot!
