### ISSUE TITLE
check_load,check_procs error on fedora27

### ISSUE THREAD

**Issue by kalinikos** [nagios-plugins/nagios-plugins#346]
Hello,
we just update our machines from fedora 26 to 27, and sadly figured out that nagios plugins check_load and check_procs  stop working with following error:

check_load - check_load -w 5,5,5 -c 10,10,10 CRITICAL - "You need more args!!! Error opening" 
check_procs - /usr/lib64/nagios/plugins/check_procs -w 350 -c 400 "Unable to read output"
On fedora26 still work fine, we try to install latest Beta(nagios-plugins-all-2.2.1-9.fc27.x86_64) nagios_plugins, but unfortunately it doesn't solve the problem 

Please, can you help us with this?

**Comment by hedenface** [comment]
Is all the check_load said was exactly...

> CRITICAL - You need more args!!! Error opening

If there wasn't anything after "Error opening" it looks like `PROC_LOADAVG` isn't being set properly. @smooge may have some insight into this - these packages for Fedora are not maintained by us.

What happens if you compile from source? Does it work then?

**Comment by kalinikos** [comment]
Hello,
so when we compile from the source, everything is getting fine and plugins work on Fedora27 just like they are on Fedora26.
I think we can close this ticket, many thanks for you help.
