### ISSUE TITLE
check_ntp_peer relies on insecure NTPd implementation

### ISSUE THREAD

**Issue by moviuro** [nagios-plugins/nagios-plugins#57]
I have a perfectly fine running ntpd OpenBSD server (check_ntp_time works wonderfully) and my nagios monitoring host complains when I check_ntp_peer:

CRITICAL - Socket timeout after 10 seconds

If I believe http://ihazem.wordpress.com/2012/12/18/nagios-check_ntp_peer-error-critical-socket-timeout-after-10-seconds/ , it is because of a "restrict" option I have no knowledge of, and that openntp does not implement for security reasons.

Best regards,
EDIT: removed a wrong example of ntp

**Comment by uetzguer** [comment]
You cannot monitor OpenNTPD with check_ntp_peer, and that is due to both their designs.

check_ntp_peer's stated purpose is to find out things about an NTP server's system peer (i.e., the server's server). OpenNTPD exposes such data only via a socket (/var/run/ntpd.sock).

check_ntp_peer, however, uses "NTP control message" packets (NTP packet mode 6, according to RFC 5905). OpenNTPD does not support NTP control messages. (Neither does chrony, the only other NTP server software I know about.)

There are two ways to fix this:

1. get OpenNTPD to implement NTP packet mode 6 (which, as far as I can tell from quick googling, is unlikely at best); or
2. extend check_ntp_peer to speak OpenNTPD's socket protocol (and even then you would have to run it on the same host as OpenNTPD).

FWIW, I think it would be better to write a seperate plugin rather than fix this "bug".

**Comment by jfrickson** [comment]
check_ntp_peer is used for checking a remote peer, so we're not going to implement unix sockets. And we need information available only in response to a control message. Closing.
