### ISSUE TITLE
Email address in help pages does not work

### ISSUE THREAD

**Issue by FrankV66** [nagios-plugins/nagios-plugins#591]
Every help page end with:
Send email to help@nagios-plugins.org if you have questions regarding use of this software. To submit patches or suggest improvements, send email to devel@nagios-plugins.org

if you send an email you receive: 

Generating server: www.nagios-plugins.org
devel@nagios-plugins.org
Remote Server returned '554 4.4.1 < #4.4.1 X-Postfix; connect to lists.nagios.com[69.164.201.132]:25: Connection timed out>'

Delivery has failed to these recipients or groups:
help@nagios-plugins.org
A communication failure occurred during the delivery of this message. Please try resending the message later. If the problem continues, contact your email admin.

**Comment by sawolf** [comment]
Thanks for reporting this. If you're looking for a mailing list in particular, I believe the other main fork of this project (monitoring-plugins) still has similar mailing lists. 

I'll see about changing the help text. Otherwise, this is the right place to discuss issues/development for this project.
