### ISSUE TITLE
check_http and checking specific certificates

### ISSUE THREAD

**Issue by guardiandigital** [nagios-plugins/nagios-plugins#635]
I'm using nagios-plugins-http-2.3.3-10 on fedora34 and trying to use it to check the validity of some of our digital certificates.

The problem is that I don't understand why it's not checking the validity period for the cert related to the domain for which I'm checking:

```
$ /usr/lib64/nagios/plugins/check_http -t 30 -S -H www.guardiandigital.com -p 443 -C 14
SSL WARNING - Certificate 'darwin-perf.guardiandigital.com' expires in 10 day(s) (2021-12-06 16:01 -0500/EST).
```

Despite passing the -H option to specify the host I want to check, it's still checking another host in that domain.

Is this related to our apache config? darwin-perf appears to be the first domain when listing them using "httpd -t -D DUMP_VHOSTS", but it's not the one I want to check.

Ideas greatly appreciated.

**Comment by guardiandigital** [comment]
Anyone have any thoughts on the above? How do I use check_http to check a specific certificate for a domain, and why doesn't this do this by default?

**Comment by sawolf** [comment]
I forgot to finish looking into this. The reason darwin-perf is shown here is because it's the first certificate you get back if you don't specify the subject name:

```
openssl s_client -showcerts -connect guardiandigital.com:443 2>/dev/null | openssl x509 -inform pem -noout -text | grep "Subject:"
        Subject: CN=darwin-perf.guardiandigital.com
```
You can use server name indication by enabling the `--sni` option, which seems to do what you want:
```
/repos/nagios-plugins/plugins/check_http -t 30 -S -H www.guardiandigital.com -p 443 -C 14 --sni
SSL OK - Certificate 'guardiandigital.com' will expire in 83 days on 2022-02-21 08:36 -0500/EST.
```
It's not turned on by default for backward compatibility reasons - this project has been around for longer than server name indication.

I'm closing this issue for now. If you have any other concerns about this, just leave another comment and we can re-open it.
