### ISSUE TITLE
nrpe issues

### ISSUE THREAD

**Issue by ls440** [nagios-plugins/nagios-plugins#671]
Hi all,

We have been using NRPE version 3 from the client and then we have updated version to 4 on all the clients. Now all the nrpe checks has an UNknown state "nrpe command not defined"

Can you please suggest.

**Comment by sawolf** [comment]
Hopefully you've already found a solution by now, but if not:
NRPE commands are usually defined in nrpe.cfg - I would guess that this file was overwritten during your upgrade process, so you'll need to find a copy that has all of your commands defined, and copy those commands into each client's nrpe.cfg.

I'm closing this issue since it's in the wrong repository. If you still have issues, please open a new issue in the [NRPE issues page](https://github.com/NagiosEnterprises/nrpe/issues) or in the [Nagios Support Forums](https://support.nagios.com/forum/).
