### ISSUE TITLE
Spec file issues

### ISSUE THREAD

**Issue by abrist** [nagios-plugins/nagios-plugins#7]
See:
http://support.nagios.com/forum/viewtopic.php?f=7&t=21809&p=86399#p86399

**Comment by tmcnag** [comment]
Claimed to have been fixed by @estanley375 in November 2013:

http://tracker.nagios.org/view.php?id=488

along with

http://tracker.nagios.org/view.php?id=487
http://tracker.nagios.org/view.php?id=489

The referenced forum thread mentions Plugins, Core, and NRPE, so the above tracker issues might inter-mingle a bit.

**Comment by tmcnag** [comment]
(The "Close and comment" button really should be moved away from the "Comment" button, or at least require confirmation...)

**Comment by jfrickson** [comment]
There haven't been any recent mentions of spec file problems. A lot of this old info is no longer relevant. If anyone is having problems, please open a new issue. Thanks!
