### ISSUE TITLE
[BUG] check_dhcp broken on BSD

### ISSUE THREAD

**Issue by cejkar** [nagios-plugins/nagios-plugins#70]
There is a bug in getting MAC address of network interface on BSD systems, where fourth parameter in sysctl() has to be size_t * and not int *. Unfortunately, using gcc -O2 the bug is hidden and contrary to compiler warning, check_dhcp seems to be working. However, when you use gcc -O0 or gcc -O1 or clang in FreeBSD 10 on amd64, the bug is exposed:

./check_dhcp -i em0 -s 127.0.0.1
Error: Couldn't get hardware address from em0. sysctl 2 error - No such file or directory.

How to submit patches? Copy and paste version is here, the fix is really easy:

--- plugins-root/check_dhcp.c.orig      2015-01-21 13:03:09.000000000 +0100
+++ plugins-root/check_dhcp.c   2015-01-21 13:03:46.000000000 +0100
@@ -326,7 +326,8 @@
 #elif defined(__bsd__)
                                                /* King 2004    see ACKNOWLEDGEMENTS */
 
-        int                     mib[6], len;
+        int                     mib[6];
+        size_t                  len;
         char                    *buf;
         unsigned char           *ptr;
         struct if_msghdr        *ifm;

**Comment by cejkar** [comment]
Uff, the patch has been completely destroyed by this intelligent/dumb system  :o( So just by words: Please change "int len" to "size_t len" in check_dhcp.c:329. Thanks.

**Comment by sreinhardt** [comment]
Github intentionally separates bugs from pull requests, as bugs do not allow for attribution of code. General pull request steps are to, fork or clone the existing repository, make and commit your changed code, then submit a pull request to the project with your alterations.
I can certainly look into these changes and see about getting them in, but you would not receive proper attribution per github, of course I would still mention you in the commit and thanks file. If that is enough for you, I can take a look and move this along, otherwise if you would submit a PR, that would be fantastic!

**Comment by abrist** [comment]
Do you wish to submit this as a PR, or should we just make the changes and add your attribution to the commit message and THANKS.in?

**Comment by wim-h** [comment]
I created a patch and submitted to nagios forums, and they directed me to this github.
Then I found out somebody else already submitted something, but this was never accepted.

I have attached a zip file, which contains a patch file. Hope that this will get included...

[nagios-plugins-2.1.1.patch.zip](https://github.com/nagios-plugins/nagios-plugins/files/94001/nagios-plugins-2.1.1.patch.zip)

**Comment by jfrickson** [comment]
Fixed on branch 'maint' via the above reference commit
